version: '3.7'
services:
  spring:
    build: .
    image: spring:202303-2
    restart: always
    container_name: spring
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    volumes:
      - ./:/srv:cached
      - root-data:/root # .bash_profileなどを永続化
    working_dir: /srv
    networks: # nginxを基準にcontainerとネットワーク共有
      nginx_default:

volumes:
  root-data:
    driver: local

networks:
  nginx_default:
    external: true
